services:
  - type: web
    name: unzipper-bot
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python3 -m unzipper
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
